"""empty message

Revision ID: bbab651c5548
Revises: 7ac0ceb4aa3c
Create Date: 2018-02-07 09:30:18.256270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbab651c5548'
down_revision = '7ac0ceb4aa3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=200), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('cc', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=10000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_template')
    # ### end Alembic commands ###
